spring:
  application:
    name: blog
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: create # Automatically reset the DB and build tables from the JPA entities on application startup. Development only.
    open-in-view: false # Close the persistence context before rendering; views must receive all required associations already loaded.

management:

  tracing:
    sampling:
      probability: 1.0

  opentelemetry:

    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs

  observations:
    annotations:
      enabled: true

  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics

blog:
  data:
    comments: 100
    posts: 20
    users: 200
    enabled: true
