# The compose file starts the database only, the java app must be started locally.
# The spring docker compose plugin should start the compose file when the application starts.

services:
  postgres:
    image: 'postgres:15.19'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
